CREATE TABLE IF NOT EXISTS eventos_convivencia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hogar_id INT NOT NULL,
    mascota_iniciadora_id INT NOT NULL,
    espacio_id INT NULL,
    recurso_id INT NULL,
    tipo_evento VARCHAR(80) NOT NULL,
    subtipo_evento VARCHAR(120) NULL,
    fecha_evento DATE NULL,
    momento_relativo VARCHAR(120) NULL,
    descripcion TEXT NULL,
    desencadenante_reportado TEXT NULL,
    nivel_intensidad VARCHAR(40) NULL,
    requiere_atencion BOOLEAN NOT NULL DEFAULT FALSE,
    requiere_seguimiento BOOLEAN NOT NULL DEFAULT TRUE,
    estado_evento VARCHAR(40) NOT NULL DEFAULT 'abierto',
    impacto_convivencia VARCHAR(60) NULL,
    resultado_inmediato TEXT NULL,
    notas TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_eventos_convivencia_hogar FOREIGN KEY (hogar_id) REFERENCES hogares(id),
    CONSTRAINT fk_eventos_convivencia_mascota_iniciadora FOREIGN KEY (mascota_iniciadora_id) REFERENCES mascotas(id),
    CONSTRAINT fk_eventos_convivencia_espacio FOREIGN KEY (espacio_id) REFERENCES hogar_espacios(id),
    CONSTRAINT fk_eventos_convivencia_recurso FOREIGN KEY (recurso_id) REFERENCES hogar_recursos_mascotas(id),
    INDEX idx_eventos_convivencia_hogar (hogar_id),
    INDEX idx_eventos_convivencia_mascota_iniciadora (mascota_iniciadora_id),
    INDEX idx_eventos_convivencia_espacio (espacio_id),
    INDEX idx_eventos_convivencia_recurso (recurso_id),
    INDEX idx_eventos_convivencia_tipo (tipo_evento),
    INDEX idx_eventos_convivencia_fecha (fecha_evento),
    INDEX idx_eventos_convivencia_estado (estado_evento),
    INDEX idx_eventos_convivencia_seguimiento (requiere_seguimiento)
);

CREATE TABLE IF NOT EXISTS involucrados_evento_convivencia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    evento_convivencia_id INT NOT NULL,
    hogar_id INT NOT NULL,
    mascota_id INT NULL,
    persona_id INT NULL,
    rol_en_evento VARCHAR(80) NULL,
    afectacion_observada TEXT NULL,
    notas TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_involucrados_evento_convivencia_al_menos_uno CHECK (mascota_id IS NOT NULL OR persona_id IS NOT NULL),
    CONSTRAINT fk_involucrados_evento_convivencia_evento FOREIGN KEY (evento_convivencia_id) REFERENCES eventos_convivencia(id),
    CONSTRAINT fk_involucrados_evento_convivencia_hogar FOREIGN KEY (hogar_id) REFERENCES hogares(id),
    CONSTRAINT fk_involucrados_evento_convivencia_mascota FOREIGN KEY (mascota_id) REFERENCES mascotas(id),
    CONSTRAINT fk_involucrados_evento_convivencia_persona FOREIGN KEY (persona_id) REFERENCES hogar_personas(id),
    INDEX idx_involucrados_evento_convivencia_evento (evento_convivencia_id),
    INDEX idx_involucrados_evento_convivencia_hogar (hogar_id),
    INDEX idx_involucrados_evento_convivencia_mascota (mascota_id),
    INDEX idx_involucrados_evento_convivencia_persona (persona_id),
    INDEX idx_involucrados_evento_convivencia_rol (rol_en_evento)
);

CREATE TABLE IF NOT EXISTS planes_evento_convivencia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    evento_convivencia_id INT NOT NULL,
    hogar_id INT NOT NULL,
    tipo_recomendacion VARCHAR(80) NULL,
    descripcion_recomendacion TEXT NULL,
    objetivo TEXT NULL,
    prioridad VARCHAR(40) NULL,
    plazo_seguimiento_dias INT NULL,
    fecha_seguimiento_sugerida DATE NULL,
    estado_plan VARCHAR(40) NOT NULL DEFAULT 'sugerido',
    fue_aplicado BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_aplicacion DATE NULL,
    resultado_reportado TEXT NULL,
    efectividad_percibida VARCHAR(40) NULL,
    requiere_ajuste BOOLEAN NOT NULL DEFAULT FALSE,
    notas TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_planes_evento_convivencia_evento FOREIGN KEY (evento_convivencia_id) REFERENCES eventos_convivencia(id),
    CONSTRAINT fk_planes_evento_convivencia_hogar FOREIGN KEY (hogar_id) REFERENCES hogares(id),
    INDEX idx_planes_evento_convivencia_evento (evento_convivencia_id),
    INDEX idx_planes_evento_convivencia_hogar (hogar_id),
    INDEX idx_planes_evento_convivencia_estado (estado_plan),
    INDEX idx_planes_evento_convivencia_aplicado (fue_aplicado),
    INDEX idx_planes_evento_convivencia_seguimiento (fecha_seguimiento_sugerida),
    INDEX idx_planes_evento_convivencia_ajuste (requiere_ajuste)
);

